### ISSUE TITLE
Why does this extension depend on the string extension?

### ISSUE THREAD

**Issue by krame505** [melt-umn/ableC-watch#1]
The test artifacts include the string extension and the test programs all include string.xh, but none seem to be using any of the extension's features.  Is there a reason for this?

**Comment by TravisCarlson** [comment]
The feature/type_qualifiers branch uses showExpr() from the string extension to display variables that are qualified as watched. This then translates to showInt(), for example, in the generated plain C code, which is why string.xh is included.

**Comment by krame505** [comment]
Ah, makes sense.  I missed that.
